
[[constraint]]
  name = "github.com/DataDog/dd-trace-go"
  version = "0.6.1"

[[constraint]]
  name = "github.com/eSailors/go-datadog"
  version = "1.0.1"

[[constraint]]
  name = "github.com/flachnetz/go-admin"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  source = "https://github.com/flachnetz/go-metrics.git"
  revision = "ff4b9a81db61c463c0cac067489b4ca763b826ef"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "0.5.2"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.15"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  version = "0.3.4"

[[constraint]]
  name = "github.com/apache/thrift"
  revision = "88591e32e710a0524327153c8b629d5b461e35e0"

[prune]
  go-tests = true
  unused-packages = true
